CREATE DATABASE segundo_projeto

USE segundo_projeto
GO

CREATE TABLE Pessoas
(
	codigo INT NOT NULL PRIMARY KEY IDENTITY,
	salario DECIMAL (10,2),
	nome VARCHAR(100) NOT NULL,
	CPF VARCHAR(10) NOT NULL,
)
GO

CREATE TABLE Clientes
(
	codigo INT NOT NULL PRIMARY KEY IDENTITY REFERENCES Pessoas,
	renda DECIMAL NOT NULL,
	credito DECIMAL NOT NULL
)
GO

CREATE TABLE Vendedores
(
	codigo INT NOT NULL PRIMARY KEY IDENTITY REFERENCES Pessoas,
	salario DECIMAL NOT NULL,
)
GO

CREATE TABLE Pedidos
(
	numero INT NOT NULL PRIMARY KEY IDENTITY,
	data DATETIME NOT NULL,
	valor DECIMAL NOT NULL,
	status INT NOT NULL
)
GO

CREATE TABLE Produtos
(
	codigo INT NOT NULL PRIMARY KEY IDENTITY,
	decricao VARCHAR(100) NOT NULL,
	valor DECIMAL(10,2) NOT NULL,
	estoque INT NOT NULL,
	status INT NOT NULL
)
GO